export const SET_USER = 'SET_USER';
export const ERRORS = 'ERRORS';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_PROFILES = 'SET_PROFILES';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const BAN_PROFILE = 'BAN_PROFILE';

//product
export const SET_PRODUCT = 'SET_PRODUCT';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const SET_COMMENT = 'SET_COMMENT';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';

//? product skander

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

// ----------

//Basket
export const ADD_TO_BASKET_REQUEST = 'ADD_TO_BASKET_REQUEST';
export const ADD_TO_BASKET_SUCCESS = 'ADD_TO_BASKET_SUCCESS';
export const ADD_TO_BASKET_FAILURE = 'ADD_TO_BASKET_FAILURE';
export const GET_BASKET_REQUEST = 'GET_BASKET_REQUEST';
export const GET_BASKET_SUCCESS = 'GET_BASKET_SUCCESS';
export const GET_BASKET_FAILURE = 'GET_BASKET_FAILURE';
export const DELETE_BASKET_REQUEST = 'DELETE_BASKET_REQUEST';
export const DELETE_BASKET_SUCCESS = 'DELETE_BASKET_SUCCESS';
export const DELETE_BASKET_FAILURE = 'DELETE_BASKET_FAILURE';

export const PUT_BASKET_REQUEST = 'PUT_BASKET_REQUEST';
export const PUT_BASKET_SUCCESS = 'PUT_BASKET_SUCCESS';
export const PUT_BASKET_FAILURE = 'PUT_BASKET_FAILURE';
export const SET_FAVORIS = 'SET_FAVORIS';
export const FETCH_FAVORIS_SUCCESS = 'FETCH_FAVORIS_SUCCESS';
export const FETCH_FAVORIS_ERROR = 'FETCH_FAVORIS_ERROR';




